licenses(["notice"])
package(default_visibility = ["//mediapipe/examples:__subpackages__"])

cc_library(
    name = "lirc_client",
    hdrs = ["lirc_client.h"],
    srcs = ["lirc_client.cc"],
    visibility = ["//visibility:public"],
)